{
"ns_property":"http://lod-apps.googlecode.com/files/face.rdf#",
"propmap":[
  {"p":["picture"],"v":["http://opengraphprotocol.org/schema/image","http://xmlns.com/foaf/0.1/depiction"],
  {"p":["name"],"v":["http://opengraphprotocol.org/schema/title","http://xmlns.com/foaf/0.1/name"],
  {"p":["link"],"v":["http://opengraphprotocol.org/schema/url","http://xmlns.com/foaf/0.1/homepage"],
  {"p":["category"],"v":["http://opengraphprotocol.org/schema/type","http://purl.org/dc/terms/type"],

  {"p":["first_name"],"v":["http://xmlns.com/foaf/0.1/firstName"],
  {"p":["last_name"],"v":["http://xmlns.com/foaf/0.1/lastName"],
  {"p":["from"],"v":["http://purl.org/dc/terms/source"],
  {"p":["id"],"v":["http://purl.org/dc/terms/identifier"],
  {"p":["created_time"],"v":["http://purl.org/dc/terms/created"],
  {"p":["updated_time"],"v":["http://purl.org/dc/terms/modified"]
],
"namespacemap":[
  {"prefix":"foaf","ns":"http://xmlns.com/foaf/0.1/"},
  {"prefix":"dcterms","ns":"http://purl.org/dc/terms/"},
  {"prefix":"og","ns":"http://opengraphprotocol.org/schema/"}
]
}